name: CD - Deploy to Production

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.0'

      - name: Build
        run: dotnet build --configuration Release

      - name: Deploy
        run: echo "Aquí iría tu paso de despliegue (FTP, SSH, Azure, etc.)"

